/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRunScheduledPlaylistsRouteImport } from './routes/api/public/hooks/run-scheduled-playlists'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunScheduledPlaylistsRoute =
  ApiPublicHooksRunScheduledPlaylistsRouteImport.update({
    id: '/api/public/hooks/run-scheduled-playlists',
    path: '/api/public/hooks/run-scheduled-playlists',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/public/hooks/run-scheduled-playlists': typeof ApiPublicHooksRunScheduledPlaylistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/public/hooks/run-scheduled-playlists': typeof ApiPublicHooksRunScheduledPlaylistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/api/public/hooks/run-scheduled-playlists': typeof ApiPublicHooksRunScheduledPlaylistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/embed'
    | '/login'
    | '/signup'
    | '/api/public/hooks/run-scheduled-playlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/embed'
    | '/login'
    | '/signup'
    | '/api/public/hooks/run-scheduled-playlists'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/embed'
    | '/login'
    | '/signup'
    | '/api/public/hooks/run-scheduled-playlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EmbedRoute: typeof EmbedRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksRunScheduledPlaylistsRoute: typeof ApiPublicHooksRunScheduledPlaylistsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-scheduled-playlists': {
      id: '/api/public/hooks/run-scheduled-playlists'
      path: '/api/public/hooks/run-scheduled-playlists'
      fullPath: '/api/public/hooks/run-scheduled-playlists'
      preLoaderRoute: typeof ApiPublicHooksRunScheduledPlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EmbedRoute: EmbedRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksRunScheduledPlaylistsRoute:
    ApiPublicHooksRunScheduledPlaylistsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
